# Generated by Django 4.1.1 on 2022-09-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlalgorithmstatus',
            name='owner',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
